import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Clock, Database, Server, RefreshCw } from 'lucide-react';
import { Card } from '../common/Card';
import { Badge } from '../common/Badge';
import { CardSkeleton } from '../common/Skeleton';
export function SystemStatusCard({ status, loading, onRefresh }) {
    if (loading)
        return _jsx(CardSkeleton, {});
    return (_jsxs(Card, { children: [_jsxs("div", { className: "flex items-center justify-between mb-3", children: [_jsx("h2", { className: "text-sm font-semibold text-text-primary", children: "\uC2DC\uC2A4\uD15C \uC0C1\uD0DC" }), _jsx("button", { onClick: onRefresh, className: "btn-ghost min-h-[36px] min-w-[36px] p-2", children: _jsx(RefreshCw, { size: 14 }) })] }), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Server, { size: 14, className: "text-text-muted" }), _jsx("span", { className: "text-xs text-text-muted", children: "\uBC31\uC5D4\uB4DC" })] }), _jsx(Badge, { variant: status.status === 'online' ? 'success' : status.status === 'warning' ? 'warning' : 'danger', children: status.status === 'online' ? 'ONLINE' : status.status === 'warning' ? 'WARNING' : 'OFFLINE' })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Clock, { size: 14, className: "text-text-muted" }), _jsx("span", { className: "text-xs text-text-muted", children: "\uAC00\uB3D9 \uC2DC\uAC04" })] }), _jsx("span", { className: "text-xs font-mono tabular-nums text-text-primary", children: status.uptime })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Database, { size: 14, className: "text-text-muted" }), _jsx("span", { className: "text-xs text-text-muted", children: "\uB370\uC774\uD130\uBCA0\uC774\uC2A4" })] }), _jsx("span", { className: "text-xs font-mono tabular-nums text-text-primary", children: status.db })] })] })] }));
}
