import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { X, TrendingUp, TrendingDown } from 'lucide-react';
import { formatKRW } from '../../utils/format';
export function TradeDrawer({ trades, open, onClose }) {
    if (!open)
        return null;
    const totalWin = trades.filter((t) => t.pnl && t.pnl > 0).length;
    const totalLoss = trades.filter((t) => t.pnl && t.pnl < 0).length;
    return (_jsxs(_Fragment, { children: [_jsx("div", { className: "fixed inset-0 z-50 bg-black/50", onClick: onClose }), _jsxs("div", { className: "fixed bottom-0 left-0 right-0 z-50 max-h-[85vh] bg-surface-card border border-surface-border rounded-t-2xl overflow-hidden animate-slide-up", children: [_jsxs("div", { className: "sticky top-0 bg-surface-card border-b border-surface-border px-5 py-3 flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-sm font-semibold text-text-primary", children: "\uC804\uCCB4 \uAC70\uB798 \uB0B4\uC5ED" }), _jsxs("p", { className: "text-[11px] text-text-muted mt-0.5", children: ["\uCD1D ", trades.length, "\uAC74 \u00B7 \uC2B9\uB9AC ", totalWin, " \u00B7 \uD328\uBC30 ", totalLoss] })] }), _jsx("button", { onClick: onClose, className: "min-h-[44px] min-w-[44px] flex items-center justify-center text-text-muted hover:text-text-primary", children: _jsx(X, { size: 20 }) })] }), _jsx("div", { className: "overflow-y-auto", style: { maxHeight: 'calc(85vh - 64px)' }, children: trades.length === 0 ? (_jsx("div", { className: "p-8 text-center text-text-muted text-sm", children: "\uAC70\uB798 \uB0B4\uC5ED\uC774 \uC5C6\uC2B5\uB2C8\uB2E4" })) : (_jsxs("table", { className: "w-full text-xs", children: [_jsx("thead", { className: "sticky top-0 bg-surface-card", children: _jsxs("tr", { className: "text-text-muted border-b border-surface-border", children: [_jsx("th", { className: "text-left px-4 py-2.5 font-medium", children: "\uC885\uBAA9" }), _jsx("th", { className: "text-right px-2 py-2.5 font-medium", children: "\uAD6C\uBD84" }), _jsx("th", { className: "text-right px-2 py-2.5 font-medium", children: "\uC218\uB7C9" }), _jsx("th", { className: "text-right px-2 py-2.5 font-medium", children: "\uAC00\uACA9" }), _jsx("th", { className: "text-right px-3 py-2.5 font-medium", children: "\uC190\uC775" }), _jsx("th", { className: "text-left px-3 py-2.5 font-medium", children: "\uC0AC\uC720" })] }) }), _jsx("tbody", { children: trades.map((t, i) => {
                                        const isBuy = t.action === 'BUY';
                                        const pnl = t.pnl ?? 0;
                                        const isPositive = pnl >= 0;
                                        return (_jsxs("tr", { className: "border-b border-surface-border hover:bg-surface-hover/40", children: [_jsx("td", { className: "px-4 py-2.5", children: _jsx("div", { className: "text-text-primary font-medium", children: t.name || t.ticker || '-' }) }), _jsx("td", { className: `px-2 py-2.5 text-right font-medium ${isBuy ? 'text-primary' : 'text-danger'}`, children: isBuy ? '매수' : '매도' }), _jsx("td", { className: "px-2 py-2.5 text-right text-text-muted font-mono tabular-nums", children: t.quantity || '-' }), _jsx("td", { className: "px-2 py-2.5 text-right text-text-primary font-mono tabular-nums", children: t.price ? formatKRW(t.price) : '-' }), _jsx("td", { className: `px-3 py-2.5 text-right font-mono tabular-nums font-medium ${isPositive ? 'text-success' : 'text-danger'}`, children: _jsxs("div", { className: "flex items-center justify-end gap-1", children: [isPositive ? _jsx(TrendingUp, { size: 11 }) : _jsx(TrendingDown, { size: 11 }), formatKRW(pnl)] }) }), _jsx("td", { className: "px-3 py-2.5 text-text-muted text-[10px]", children: _jsx("span", { className: "bg-surface border border-surface-border rounded px-1.5 py-0.5", children: t.reason || '-' }) })] }, t.id || i));
                                    }) })] })) })] })] }));
}
