import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { X, HelpCircle, ChevronDown, ChevronUp } from 'lucide-react';
export function HelpDrawer({ content, open, onClose }) {
    const [expandedFaq, setExpandedFaq] = useState(null);
    if (!open)
        return null;
    return (_jsx("div", { className: "fixed inset-0 z-50 flex items-end sm:items-center justify-center bg-black/40", onClick: onClose, children: _jsxs("div", { className: "bg-surface-card w-full sm:max-w-lg rounded-t-2xl sm:rounded-2xl max-h-[85vh] overflow-y-auto border border-surface-border", onClick: e => e.stopPropagation(), children: [_jsxs("div", { className: "sticky top-0 bg-surface-card border-b border-surface-border px-4 py-3 flex items-center justify-between z-10", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(HelpCircle, { size: 16, className: "text-primary" }), _jsxs("h3", { className: "text-sm font-bold text-text", children: [content.title, " \uB3C4\uC6C0\uB9D0"] })] }), _jsx("button", { onClick: onClose, className: "p-1 text-text-muted hover:text-text", children: _jsx(X, { size: 16 }) })] }), _jsxs("div", { className: "p-4 space-y-4 text-xs", children: [_jsx(Section, { title: "\uD654\uBA74 \uBAA9\uC801", children: _jsx("p", { className: "text-text-muted leading-relaxed", children: content.purpose }) }), _jsx(Section, { title: "\uC8FC\uC694 \uAE30\uB2A5", children: _jsx("ul", { className: "space-y-1.5", children: content.features.map((f, i) => (_jsxs("li", { className: "flex items-start gap-2 text-text-muted", children: [_jsx("span", { className: "text-primary mt-0.5", children: "\u2022" }), _jsx("span", { children: f })] }, i))) }) }), _jsx(Section, { title: "\uC0AC\uC6A9 \uBC29\uBC95", children: _jsx("ol", { className: "space-y-1.5 list-decimal list-inside text-text-muted", children: content.howToUse.map((step, i) => (_jsx("li", { children: step }, i))) }) }), content.indicators.length > 0 && (_jsx(Section, { title: "\uC8FC\uC694 \uC9C0\uD45C \uC124\uBA85", children: _jsx("div", { className: "space-y-2", children: content.indicators.map((ind, i) => (_jsxs("div", { className: "bg-surface rounded-lg px-3 py-2", children: [_jsx("div", { className: "text-text font-medium mb-0.5", children: ind.name }), _jsx("div", { className: "text-text-muted leading-relaxed", children: ind.desc })] }, i))) }) })), content.faq.length > 0 && (_jsx(Section, { title: "\uC790\uC8FC \uBB3B\uB294 \uC9C8\uBB38", children: _jsx("div", { className: "space-y-1", children: content.faq.map((item, i) => (_jsxs("div", { className: "bg-surface rounded-lg overflow-hidden", children: [_jsxs("button", { onClick: () => setExpandedFaq(expandedFaq === i ? null : i), className: "w-full flex items-center justify-between px-3 py-2.5 text-left text-text font-medium", children: [_jsxs("span", { className: "pr-2", children: ["Q. ", item.q] }), expandedFaq === i ? _jsx(ChevronUp, { size: 14, className: "shrink-0" }) : _jsx(ChevronDown, { size: 14, className: "shrink-0" })] }), expandedFaq === i && (_jsxs("div", { className: "px-3 pb-2.5 text-text-muted leading-relaxed border-t border-surface-border pt-2", children: ["A. ", item.a] }))] }, i))) }) }))] })] }) }));
}
function Section({ title, children }) {
    return (_jsxs("div", { children: [_jsx("h4", { className: "text-xs font-semibold text-text-muted uppercase tracking-wider mb-2", children: title }), children] }));
}
